"""init schema

Revision ID: 057c3d8e9653
Revises: 
Create Date: 2026-01-07 11:06:34.845144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '057c3d8e9653'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'popups',
                sa.JSON(),
                nullable=False,
                server_default=sa.text("'[]'"),  # SQLite requires default when adding NOT NULL
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_column('popups')

    # ### end Alembic commands ###
